title: LibreQuake
logo: /assets/img/logo.png
description: [not ready for commercial use] A freesoftware quake one remake with art under the BSD license
show_downloads: true
google_analytics: true
theme: jekyll-theme-minimal
